name: Playwright Tests CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1, 2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run Playwright tests (shard ${{ matrix.shard }})
        run: |
          docker run --rm \
            -e CI=true \
            -e PW_SHARD_INDEX=${{ matrix.shard }} \
            -e PW_SHARD_TOTAL=2 \
            -v ${{ github.workspace }}/allure-results:/app/allure-results \
            playwright-tests npx playwright test --shard=${{ matrix.shard }}/2

      - name: Generate Allure report
        if: always()
        run: |
          docker run --rm -v ${{ github.workspace }}/allure-results:/app/allure-results -v ${{ github.workspace }}/reports:/app/reports playwright-tests npx allure generate ./allure-results -o ./reports --clean


      - name: Upload Allure report artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report-${{ matrix.shard }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: ./reports
